// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bkbbpfsujqpusioqrbwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYmJwZnN1anFwdXNpb3FyYndyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDc4MDUsImV4cCI6MjA2OTQyMzgwNX0.O6CRo_R3asr8Ka2psK95eT0Ux8DiSmeVgBmhoS9tWdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);